- hosts: control_plane
  become: yes
  vars_files:
    - vars/common_vars.yaml
  tasks:

    - name: Get IMDSv2 token
      shell: 'curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"'
      register: token
    
    - name: Get private IP address of EC2 instance
      shell: 'curl -H "X-aws-ec2-metadata-token: {{ token.stdout }}" http://169.254.169.254/latest/meta-data/local-ipv4'
      register: private_ip
      
    # - name: Gather private IP address of EC2 instance
    #   command: curl -s http://169.254.169.254/latest/meta-data/local-ipv4
    #   register: private_ip

    - name: initialize the cluster
      shell: sudo kubeadm init --apiserver-advertise-address={{ private_ip.stdout }} --ignore-preflight-errors=Mem >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      file:
        path: /home/k8sadmin/.kube
        state: directory
        mode: 0755
        owner: k8sadmin
        group: k8sadmin

    - name: copy admin.conf
      copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: /home/k8sadmin/.kube/config
        owner: k8sadmin



    - name: Install Weave Pod network
      become: yes
      shell:  kubectl apply -f https://reweave.azurewebsites.net/k8s/v{{ kubernetes_version}}/net.yaml

    - name: Get join token
      become: yes
      become_user: k8sadmin
      become_method: su
      shell: sudo kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777