- hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Ensure IPv4 packet forwarding
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.ipv4.ip_forward = 1
        EOF

        # Apply sysctl params without reboot
        sudo sysctl --system