- hosts: control_plane
  become_user: k8sadmin
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars/common_vars.yaml
    
  tasks:
    - name: Install required system packages
      become_user: root
      become: yes
      apt:
        update_cache: yes
        name:
          - python3-kubernetes
          - python3-yaml
          - python3-jsonpatch
          - python3-openshift
        state: present

    - name: Deploy NGINX Ingress Controller
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('url', 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0/deploy/static/provider/baremetal/deploy.yaml') }}"
    
    - name: Get DOCKER info
      set_fact:
        docker_user: "{{ lookup('env', 'ANSIBLE_DOCKER_USER') }}"
        docker_password: "{{ lookup('env', 'ANSIBLE_DOCKER_PASSWORD') }}"
        docker_email: "{{ lookup('env', 'ANSIBLE_DOCKER_EMAIL') }}"
      no_log: true
    
    - name: Add Docker secrets to pull image
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: dockerhub-secret
            namespace: default
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ {'auths': {'https://index.docker.io/v1/': {'username': {{docker_user}}, 'password': {{docker_password}}, 'email': {{docker_email}}}}} | to_json | b64encode }}"