- hosts: control_plane
  become: yes
  become_user: k8sadmin
  tasks:
    - name: Install helm
      become_user: root
      apt:
        name: helm
        state: present
        update_cache: yes

    - name: Add Helm repositories (prometheus and graphana)
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

    - name: Install Prometheus using Helm
      shell: |
        helm install prometheus prometheus-community/prometheus \
          --namespace monitoring \
          --create-namespace

    - name: Get Graphana password
      set_fact:
        graphana_password_env: "{{ lookup('env', 'ANSIBLE_GRAPHANA_PASSWORD') }}"

    - name: Install Grafana using Helm
      shell: |
        helm install grafana grafana/grafana \
          --namespace monitoring \
          --set service.type=ClusterIP \
          --set persistence.enabled=true \
          --set adminPassword={{ graphana_password_env}}

    # - name: Change Service 
    #   kubernetes.core.k8s:
    #     api_version: v1
    #     kind: Service
    #     namespace: argocd
    #     name: argocd-server
    #     definition:
    #       spec:
    #         type: NodePort
    #         ports:
    #         - name: http
    #           port: 80
    #           protocol: TCP
    #           targetPort: 8080
    #           nodePort: 30080
    #         - name: https
    #           port: 443
    #           protocol: TCP
    #           targetPort: 8080
    #           nodePort: 30443
    #     state: patched
