---
- hosts: all
  become: yes
  vars:
    containerd_version: "2.0.1"
    runc_version: "v1.2.3"
    cni_version: "v1.6.1"
    arch: "amd64"

  tasks:
    # Création des répertoires nécessaires
    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/cni/bin
        - /usr/local/lib/systemd/system

    # Installation de containerd
    - name: Download containerd
      get_url:
        url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-{{ arch }}.tar.gz"
        dest: /tmp/containerd.tar.gz
        mode: '0644'

    - name: Extract containerd
      unarchive:
        src: /tmp/containerd.tar.gz
        dest: /usr/local
        remote_src: yes

    # Installation de runc
    - name: Download runc
      get_url:
        url: "https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.{{ arch }}"
        dest: /tmp/runc
        mode: '0644'

    - name: Install runc
      copy:
        src: /tmp/runc
        dest: /usr/local/sbin/runc
        mode: '0755'
        remote_src: yes

    # Installation des plugins CNI
    - name: Download CNI plugins
      get_url:
        url: "https://github.com/containernetworking/plugins/releases/download/{{ cni_version }}/cni-plugins-linux-{{ arch }}-{{ cni_version }}.tgz"
        dest: /tmp/cni-plugins.tgz
        mode: '0644'

    - name: Extract CNI plugins
      unarchive:
        src: /tmp/cni-plugins.tgz
        dest: /opt/cni/bin
        remote_src: yes

    # Configuration du service systemd
    - name: Download containerd service file
      get_url:
        url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        dest: /usr/local/lib/systemd/system/containerd.service
        mode: '0644'

    # Activation du service
    - name: Start and enable containerd service
      systemd:
        name: containerd
        state: started
        enabled: yes
        daemon_reload: yes

    # Nettoyage
    - name: Clean temporary files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/containerd.tar.gz
        - /tmp/runc
        - /tmp/cni-plugins.tgz