---
- hosts: all
  become: yes
  vars_files:
    - vars/common_vars.yaml

  tasks:
    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/cni/bin
        - /usr/local/lib/systemd/system
        - /etc/containerd

    - name: Download containerd
      get_url:
        url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-{{ arch }}.tar.gz"
        dest: /tmp/containerd.tar.gz
        mode: '0644'

    - name: Extract containerd
      unarchive:
        src: /tmp/containerd.tar.gz
        dest: /usr/local
        remote_src: yes

    - name: Download runc
      get_url:
        url: "https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.{{ arch }}"
        dest: /tmp/runc
        mode: '0644'

    - name: Install runc
      copy:
        src: /tmp/runc
        dest: /usr/local/sbin/runc
        mode: '0755'
        remote_src: yes

    - name: Download CNI plugins
      get_url:
        url: "https://github.com/containernetworking/plugins/releases/download/{{ cni_version }}/cni-plugins-linux-{{ arch }}-{{ cni_version }}.tgz"
        dest: /tmp/cni-plugins.tgz
        mode: '0644'

    - name: Extract CNI plugins
      unarchive:
        src: /tmp/cni-plugins.tgz
        dest: /opt/cni/bin
        remote_src: yes

    - name: Download containerd service file
      get_url:
        url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        dest: /usr/local/lib/systemd/system/containerd.service
        mode: '0644'

    - name: Start and enable containerd service
      systemd:
        name: containerd
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Clean temporary files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/containerd.tar.gz
        - /tmp/runc
        - /tmp/cni-plugins.tgz
    
    - name: Supprimer /etc/containerd/config.toml s'il existe
      file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Créer /etc/containerd/config.toml avec le contenu requis
      copy:
        dest: /etc/containerd/config.toml
        content: |
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true
        owner: root
        group: root
        mode: '0644'
    
    # restart containerd
    - name: Redémarrer containerd
      systemd:
        name: containerd
        state: restarted