- hosts: control_plane
  become: yes
  become_user: k8sadmin
  gather_facts: yes
  tasks:
    # - name: Ensure /etc/apt/trusted.gpg.d directory exists
    #   become_user: root 
    #   become: yes
    #   file:
    #     path: /etc/apt/trusted.gpg.d
    #     state: directory
    #     mode: '0755'

    # - name: Install required packages
    #   become_user: root 
    #   become: yes
    #   apt:
    #     name: 
    #       - apt-transport-https
    #       - ca-certificates
    #       - curl
    #       - gnupg
    #     state: present
    #     update_cache: yes

    # - name: Add Helm GPG key
    #   become_user: root 
    #   become: yes
    #   shell: |
    #     curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    #   args:
    #     creates: /usr/share/keyrings/helm.gpg

    # - name: Add Helm repository
    #   become_user: root 
    #   become: yes
    #   apt_repository:
    #     repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    #     state: present
    #     filename: helm-stable-debian
    
    # - name: Update apt cache
    #   become_user: root
    #   become: yes
    #   apt:
    #     update_cache: yes

    # - name: Install Helm
    #   become_user: root
    #   become: yes
    #   apt:
    #     name: helm
    #     state: present
    #     update_cache: yes 
    - name: Install Helm via script
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

      ##########

    - name: Add Helm repositories (prometheus and graphana)
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

    - name: Install Prometheus using Helm
      shell: |
        helm install prometheus prometheus-community/prometheus \
          --namespace monitoring \
          --create-namespace

    - name: Get Graphana password
      set_fact:
        graphana_password_env: "{{ lookup('env', 'ANSIBLE_GRAPHANA_PASSWORD') }}"

    - name: Install Grafana using Helm
      shell: |
        helm install grafana grafana/grafana \
          --namespace monitoring \
          --set service.type=ClusterIP \
          --set adminPassword={{ graphana_password_env}}

    - name: Change Service 
      kubernetes.core.k8s:
        api_version: v1
        kind: Service
        namespace: monitoring
        name: prometheus-server
        definition:
          spec:
            type: NodePort
            ports:
            - name: http
              port: 80
              protocol: TCP
              targetPort: 9090
              nodePort: 32562
            - name: https
              port: 443
              protocol: TCP
              targetPort: 9090
              nodePort: 30443
        state: patched

    - name: Change Service 
      kubernetes.core.k8s:
        api_version: v1
        kind: Service
        namespace: monitoring
        name: graphana
        definition:
          spec:
            type: NodePort
            ports:
            - name: http
              port: 80
              protocol: TCP
              targetPort: 3000
              nodePort: 31587
            - name: https
              port: 443
              protocol: TCP
              targetPort: 3000
              nodePort: 33443
        state: patched
