- hosts: all
  become: yes
  tasks:
    - name: Update apt-get cache
      apt:
        update_cache: yes

    - name: Install vim
      apt:
        name: vim
        state: present
    
    - name: Create or modify ~/.vimrc file for the user
      copy:
        dest: "/home/k8sadmin/.vimrc"
        content: |
          set expandtab
          set tabstop=2
          set shiftwidth=2
          set number
        owner: k8sadmin
        group: k8sadmin
        mode: '0644'
        force: yes

    - name: Allow auto-completion kubernetes
      become: yes
      become_user: k8sadmin
      shell: grep -qxF "source <(kubectl completion bash)" ~/.bashrc || echo "source <(kubectl completion bash)" >> ~/.bashrc
        #-q: quiet mode (produces no output)
        #-x: matches the entire line
        #-F: interprets the pattern as a fixed string, not a regular expression
    
    
