- hosts: all
  become: yes
  tasks:
    - name: Update apt-get cache
      apt:
        update_cache: yes

    - name: Install vim
      apt:
        name: vim
        state: present
    
    - name: Create or modify ~/.vimrc file for the user
      copy:
        dest: "/home/k8sadmin/.vimrc"
        content: |
          set expandtab
          set tabstop=2
          set shiftwidth=2
          set number
        owner: k8sadmin
        group: k8sadmin
        mode: '0644'
        force: yes

    - name: Allow auto-completion kubernetes
      become: yes
      become_user: k8sadmin
      shell: grep -qxF "source <(kubectl completion bash)" ~/.bashrc || echo "source <(kubectl completion bash)" >> ~/.bashrc
        #-q: quiet mode (produces no output)
        #-x: matches the entire line
        #-F: interprets the pattern as a fixed string, not a regular expression
    
    - name: Créer un secret Kubernetes
      set_fact:
        aws_access_key_id: "{{ lookup('env', 'ANSIBLE_AWS_ACCESS_KEY_ID') }}"
        aws_secret_access_key: "{{ lookup('env', 'ANSIBLE_AWS_SECRET_ACCESS_KEY') }}"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: aws-credentials
            namespace: default  
          type: Opaque
          stringData:
            AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
            AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
