- hosts: workers
  become: yes

  tasks:
    - name: Copy join command from Ansible host to the worker nodes
      become: yes
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Check if the join_cluster.txt file exists
      user: k8sadmin
      stat:
        path: ~/join_cluster.txt
      register: join_file_status

    - name: Debug - Show join file status
      debug:
        msg: "Join file exists: {{ join_file_status.stat.exists }}"

    - name: Join the Worker nodes to the cluster
      user: k8sadmin
      command: sh /tmp/kubernetes_join_command
      when: not join_file_status.stat.exists
      register: join_result
      changed_when: join_result.rc == 0

    - name: Debug - Show join command result
      debug:
        var: join_result
      when: not join_file_status.stat.exists

    - name: Create the join_cluster.txt file
      user: k8sadmin
      file:
        path: ~/join_cluster.txt
        state: touch
      when: not join_file_status.stat.exists

    - name: Remove the join command file
      file:
        path: /tmp/kubernetes_join_command
        state: absent