pipeline {
    agent any
    
    tools {
        nodejs 'NodeJS'
    }
    
    environment {
        SCANNER_HOME= tool 'sonar-scanner'
    }

    stages {
        stage('Git Checkout') {
            steps {
                git credentialsId: 'github-token', url: 'git@github.com:Zeeward41/ZeeUrl.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }
        
       stage('Unit Tests') {
            steps {
                dir('frontend') {
                    sh 'npm run test-vite'
                }
            }
        }
       
        
        stage('File System Scan') {
            steps {
                dir('frontend') {
                    sh 'trivy fs --format table -o trivy-fs-frontend-report.html .'
                }
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                dir('frontend') {
                    withSonarQubeEnv('sonarQube'){
                        sh ' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=ZeeURL-Frontend -Dsonar.projectKey=ZeeURL-Frontend '
                    }
                }
            }
        }
        
        stage('Quality Code') {
            steps {
                dir('frontend') {
                    script {
                        waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'
                    }
                }
            }
        }
        
        stage('OWASP Dependency Check') {
            steps {
                withCredentials([string(credentialsId: 'nvd-api-key', variable: 'NVD_API_KEY')]) {
                    dir('backend') {
                        dependencyCheck(
                            additionalArguments: "--scan ./ --nvdApiKey ${NVD_API_KEY}",
                            odcInstallation: 'OWASP-DC'
                        )
                        dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
                    }
                }
            }
        }
        
        stage('Build and Tag Docker Image') {
            steps {
                dir('frontend') {
                    script {
                        withDockerRegistry(credentialsId: 'dockerHub-cred', toolName: 'docker') {
                            sh "docker build -t zeeward41/test:frontend_v1 ."
                        }
                    }
                }
            }
        }
        
        stage('Docker Image Scan') {
            steps {
                dir('frontend') {
                    sh 'trivy image --format table -o trivy-image-frontend-report.html zeeward41/test:frontend_v1'
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                dir('frontend') {
                    script {
                        withDockerRegistry(credentialsId: 'dockerHub-cred', toolName: 'docker') {
                                sh "docker push zeeward41/test:frontend_v1"
                        }
                    }
                }
            }
        }

        

    
    
}
}
