apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  RANGE_SERVER: "http://range-service.default.svc.cluster.local:8000"
  #FRONTEND_SERVER: "http://13.60.23.37:31423/"
  FRONTEND_SERVER: "http://k8s-ingress-alb-162867674.eu-north-1.elb.amazonaws.com"