apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  #VITE_BACKEND_API_URL: "http://13.60.23.37:31423/api"
  #VITE_FRONTEND_URL: "http://13.60.23.37:31423/"
  VITE_BACKEND_API_URL: "https://zeeurl/api"
  VITE_FRONTEND_URL: "https://zeeurl.com"