apiVersion: batch/v1
kind: CronJob
metadata:
  name: save-mongodb
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongo-export
            image: mongo:8.0.4
            command:
            - /bin/sh
            - -c
            - |
              mongoexport --host mongodb-service --port 27017 --db ZeeurlDB --collection linkurls --out /data/db/ZeeurlDB.linkurls.json --jsonArray
              mongoexport --host mongodb-service --port 27017 --db ZeeurlDB --collection linkvisits --out /data/db/ZeeurlDB.linkvisits.json --jsonArray
              mongoexport --host mongodb-service --port 27017 --db ZeeurlDB --collection users --out /data/db/ZeeurlDB.users.json --jsonArray
            volumeMounts:
            - name: data
              mountPath: /data/db
          - name: save-mongodb
            image: amazon/aws-cli:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
              aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
              aws configure set default.region eu-north-1
              sleep 10
              aws s3 cp /data/db/ZeeurlDB.linkurls.json s3://zeeurl-41-db/ZeeurlDB.linkurls.json
              aws s3 cp /data/db/ZeeurlDB.linkvisits.json s3://zeeurl-41-db/ZeeurlDB.linkvisits.json
              aws s3 cp /data/db/ZeeurlDB.users.json s3://zeeurl-41-db/ZeeurlDB.users.json
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            volumeMounts:
            - name: data
              mountPath: /data/db
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: mongodb-pvc
          restartPolicy: OnFailure