---
- hosts: sonarqube
  become: true
  tasks:
    - name: Update and Upgrade
      apt:
        update_cache: yes
        name: '*'
        state: latest


# Installation des prérequis
    - name: Installation des dépendances
      apt:
        name:
          - curl
          - gnupg
          - ca-certificates
          - gpg
        state: present
        update_cache: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
        
    - name: Make sure Docker is started
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Start SonarQube container
      shell: |
        docker run -d -p 9000:9000 sonarqube:lts-community