- hosts: control_plane
  become: yes
  vars_files:
    - vars/common_vars.yaml
    
  tasks:
    - name: Deploy NGINX Ingress Controller
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('url', 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-{{ nginx_ingress }}/deploy/static/provider/baremetal/deploy.yaml') }}"
      register: ingress_deployment