name          = "zeeward41"
project_name  = "zeeurl"
environment   = "cd"
region        = "eu-north-1"
ami_instance  = "ami-08eb150f611ca277f"
instance_type_workers = "t3.micro"
instance_type_master = "t3.small"
mon_ip = "0.0.0.0/0"