name: Install Servers CI - Jenkins and SonarQube
# on:
# push:
#   paths:
#     - 'infrastructure/CI/**'
#     - '.github/workflows/install_servers_ci.yaml'
on: workflow_dispatch
jobs:
    config_Server:
        runs-on: ubuntu-latest

        env:
            TF_VERSION: '1.10.1'
            AWS_REGION: 'eu-west-3'
        steps:
            - name: get github code
              uses: actions/checkout@v4

            - name: Get Runner IP
              id: get_ip_runner
              run: |
                  RUNNER_IP=$(curl -s https://api.ipify.org)
                  echo "runner_ip=$RUNNER_IP" >> $GITHUB_OUTPUT

            - name: Config AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: get Variables
              id: get_variables
              env:
                  GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
              run: |
                  # ami instance
                  INSTANCE_AMI=$(gh variable get AMI_INSTANCE)
                  echo "ami_instance=$INSTANCE_AMI" >> $GITHUB_OUTPUT

                  # environment
                  ENVI=$(gh variable get ENVIRONMENT)
                  echo "environment=$ENVI" >> $GITHUB_OUTPUT

                  # instance Type
                  TYPE_INSTANCE=$(gh variable get INSTANCE_TYPE)
                  echo "instance_type=$TYPE_INSTANCE" >> $GITHUB_OUTPUT

                  # Name
                  ADMIN_NAME=$(gh variable get NAME)
                  echo "name=$ADMIN_NAME" >> $GITHUB_OUTPUT

                  # Project Name
                  NAME_PROJECT=$(gh variable get PROJECT_NAME)
                  echo "project_name=$NAME_PROJECT" >> $GITHUB_OUTPUT

            - name: Create env.tfvars
              run: |
                  cat <<EOF > infrastructure/CI/terraform/env.tfvars
                  name = "${{ steps.get_variables.outputs.name}}"
                  project_name  = "${{ steps.get_variables.outputs.project_name}}"
                  environment   = "${{ steps.get_variables.outputs.environment}}"
                  region        = "${{ env.AWS_REGION}}"
                  ami_instance  = "${{ steps.get_variables.outputs.ami_instance}}"
                  instance_type = "${{ steps.get_variables.outputs.instance_type}}"
                  mon_ip = "${{ secrets.MY_IP}}"
                  EOF

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ env.TF_VERSION}}

            - name: Terraform init
              run: terraform init
              working-directory: infrastructure/CI/terraform

            - name: Terraform Format
              run: terraform fmt
              working-directory: infrastructure/CI/terraform

            - name: Terraform Validate
              run: terraform validate
              working-directory: infrastructure/CI/terraform

            - name: Terraform Plan
              run: terraform plan -var-file=env.tfvars -out=tfplan
              working-directory: infrastructure/CI/terraform

            - name: Terraform apply
              if: github.ref == 'refs/heads/master'
              run: terraform apply -var-file=env.tfvars -auto-approve tfplan
              working-directory: infrastructure/CI/terraform

            - name: get IP servers jenkins and sonarQube
              id: get_ip_servers
              run: |
                  FILE_IP_JENKINS=$(cat infrastructure/CI/terraform/ip_jenkins_server.txt)
                  FILE_IP_SONARQUBE=$(cat infrastructure/CI/terraform/ip_sonarQube_server.txt)
                  # Store data as Output
                  echo file_ip_jenkins=$FILE_IP_JENKINS >> $GITHUB_OUTPUT
                  echo file_ip_sonarQube=$FILE_IP_SONARQUBE >> $GITHUB_OUTPUT

            - name: Get group name SG servers Jenkins and SonarQube
              id: get_group_name
              run: |
                  GROUP_NAME_JENKINS=$(cat infrastructure/CI/terraform/group_name_jenkins_SG.txt | tr -d '\r' | xargs)
                  GROUP_NAME_SONARQUBE=$(cat infrastructure/CI/terraform/group_name_sonarQube_SG.txt | tr -d '\r' | xargs)
                  # Vérification de sécurité pour le debug
                  if [ -z "$GROUP_NAME_JENKINS" ]; then echo "ERREUR: Nom SG Jenkins vide"; exit 1; fi
                  # Store data as Output
                  echo "file_group_name_jenkins=$GROUP_NAME_JENKINS" >> $GITHUB_OUTPUT
                  echo "file_group_name_sonarQube=$GROUP_NAME_SONARQUBE" >> $GITHUB_OUTPUT

            - name: Add Github Runner IP to SG servers (sonarQube and Jenkins)
              run: |
                  aws ec2 authorize-security-group-ingress --group-name ${{steps.get_group_name.outputs.file_group_name_jenkins}} --protocol tcp --port 22 --cidr ${{steps.get_ip_runner.outputs.runner_ip}}/32
                  aws ec2 authorize-security-group-ingress --group-name ${{steps.get_group_name.outputs.file_group_name_sonarQube}} --protocol tcp --port 22 --cidr ${{steps.get_ip_runner.outputs.runner_ip}}/32

            - name: Add IP SonarQube to SG Jenkins servers (TCP - port 8080)
              run: |

                  # check if rule with 8080 port exists
                  RULE_EXISTS=$(aws ec2 describe-security-groups \
                    --group-names ${{steps.get_group_name.outputs.file_group_name_jenkins}} \
                    --query 'SecurityGroups[0].IpPermissions[?FromPort==`8080`].IpRanges[*].CidrIp' \
                    --output text)

                  # if rule exists then check if the rule target ip is sonarQube server.
                  if echo "$RULE_EXISTS" | grep -q "${{steps.get_ip_servers.outputs.file_ip_sonarQube}}/32"; then
                    echo "The rule already exists - skipping"
                  else
                    echo "Adding new Security Group Rule..."
                    aws ec2 authorize-security-group-ingress \
                      --group-name ${{steps.get_group_name.outputs.file_group_name_jenkins}} \
                      --protocol tcp \
                      --port 8080 \
                      --cidr ${{steps.get_ip_servers.outputs.file_ip_sonarQube}}/32
                    echo "Rule added successfully"
                  fi

            - name: Add IP Jenkins to SG SonarQube servers (TCP - port 9000)
              run: |

                  # check if rule with 9000 port exists
                  RULE_EXISTS=$(aws ec2 describe-security-groups \
                    --group-names ${{steps.get_group_name.outputs.file_group_name_sonarQube}} \
                    --query 'SecurityGroups[0].IpPermissions[?FromPort==`9000`].IpRanges[*].CidrIp' \
                    --output text)

                  # if rule exists then check if the rule target ip is Jenkins server.
                  if echo "$RULE_EXISTS" | grep -q "${{steps.get_ip_servers.outputs.file_ip_jenkins}}/32"; then
                    echo "The rule already exists - skipping"
                  else
                    echo "Adding new Security Group Rule..."
                    aws ec2 authorize-security-group-ingress \
                      --group-name ${{steps.get_group_name.outputs.file_group_name_sonarQube}} \
                      --protocol tcp \
                      --port 9000 \
                      --cidr ${{steps.get_ip_servers.outputs.file_ip_jenkins}}/32
                    echo "Rule added successfully"
                  fi

            - name: Get Private Key
              id: read_file
              run: |
                  if [ -f infrastructure/CI/terraform/la_clef_private.pem ]; then
                    FILE_CONTENT=$(base64 -w 0 infrastructure/CI/terraform/la_clef_private.pem)

                    # store data as Output
                    echo "$FILE_CONTENT"
                    echo file_content=$FILE_CONTENT >> $GITHUB_OUTPUT
                  else
                    echo "File not Found"
                    exit 0
                  fi

            - name: Get DNS instance Jenkins and SonarQube
              id: get_dns
              run: |
                  FILE_DNS_JENKINS=$(cat infrastructure/CI/terraform/dns_instance_jenkins.txt)
                  FILE_DNS_SONARQUBE=$(cat infrastructure/CI/terraform/dns_instance_sonarqube.txt)
                  # Store data as Output
                  echo file_dns_jenkins=$FILE_DNS_JENKINS >> $GITHUB_OUTPUT
                  echo file_dns_sonarqube=$FILE_DNS_SONARQUBE >> $GITHUB_OUTPUT

            - name: Add SSH Key to Github Secrets
              env:
                  GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
                  SSH_KEY: ${{ steps.read_file.outputs.file_content }}
              run: |
                  SSH_KEY=$(echo "$SSH_KEY" | base64 -d)
                  gh secret set SSH_PRIVATE_KEY --body "$SSH_KEY"

            - name: install Ansible and Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y ansible python3-pip
                  pip3 install boto3 botocore

            - name: Setup SSH key Jenkins and SonarQube
              env:
                  SSH_KEY: ${{ steps.read_file.outputs.file_content }}
                  INSTANCE_DNS_JENKINS: ${{ steps.get_dns.outputs.file_dns_jenkins}}
                  INSTANCE_DNS_SONARQUBE: ${{ steps.get_dns.outputs.file_dns_sonarqube}}
              run: |
                  mkdir -p /home/runner/.ssh/
                  chmod 700 /home/runner/.ssh/

                  echo $SSH_KEY | base64 -d > /home/runner/.ssh/key_ssh

                  chmod 400 /home/runner/.ssh/key_ssh


                  # add key to SSH agent
                  eval "$(ssh-agent -s)"
                  ssh-add /home/runner/.ssh/key_ssh

                  # Verify key format
                  ssh-keygen -y -f /home/runner/.ssh/key_ssh || echo "Error Validation key"

                  # Add host key
                  ssh-keyscan -t rsa,dsa,ecdsa,ed25519 $INSTANCE_DNS_JENKINS >> /home/runner/.ssh/known_hosts
                  ssh-keyscan -t rsa,dsa,ecdsa,ed25519 $INSTANCE_DNS_SONARQUBE >> /home/runner/.ssh/known_hosts
                  #

            - name: Run Ansible Playbook
              env:
                  INSTANCE_DNS_JENKINS: ${{ steps.get_dns.outputs.file_dns_jenkins}}
                  INSTANCE_DNS_SONARQUBE: ${{ steps.get_dns.outputs.file_dns_sonarqube}}
                  SSH_KKEY: ${{ steps.read_file.outputs.file_content }}
              run: |
                  # chmod 400 infrastructure/CI/terraform/la_clef_private.pem
                  echo "$SSH_KKEY" | base64 -d > /home/runner/my_key.pem
                  chmod 400 /home/runner/my_key.pem

                  # Creation config SSH (alias)
                  echo "Config SSH Alias"
                  mkdir -p ~/.ssh
                  cat <<-EOF > ~/.ssh/config
                  Host jenkins
                    Hostname $INSTANCE_DNS_JENKINS
                    User ubuntu
                    IdentityFile /home/runner/my_key.pem
                    StrictHostKeyChecking no

                  Host sonarqube
                    Hostname $INSTANCE_DNS_SONARQUBE
                    User ubuntu
                    IdentityFile /home/runner/my_key.pem
                    StrictHostKeyChecking no
                  EOF

                  cat /home/runner/.ssh/config

                  # Creation inventory
                  echo "Creation inventory"
                  echo -e "[jenkins_group]\njenkins ansible_host=jenkins" > infrastructure/CI/ansible/inventory
                  echo -e "[sonarqube_group]\nsonarqube ansible_host=sonarqube" >> infrastructure/CI/ansible/inventory
                  cat infrastructure/CI/ansible/inventory

                  #Run ansible
                  export ANSIBLE_HOST_KEY_CHECKING=False

                  echo "Install and Configure Jenkins"
                  ansible-playbook -i infrastructure/CI/ansible/inventory infrastructure/CI/ansible/configuration_jenkins.yaml

                  echo "Install Trivy on Jenkins Server"
                  ansible-playbook -i infrastructure/CI/ansible/inventory infrastructure/CI/ansible/install_trivy.yaml

                  echo "Install and Configure SonarQube"
                  ansible-playbook -i infrastructure/CI/ansible/inventory infrastructure/CI/ansible/configuration_sonarqube.yaml

            - name: Delete Github Actions IP to SG
              run: |
                  aws ec2 revoke-security-group-ingress --group-name ${{steps.get_group_name.outputs.file_group_name_jenkins}} --protocol tcp --port 22 --cidr ${{steps.get_ip_runner.outputs.runner_ip}}/32
                  aws ec2 revoke-security-group-ingress --group-name ${{steps.get_group_name.outputs.file_group_name_sonarQube}} --protocol tcp --port 22 --cidr ${{steps.get_ip_runner.outputs.runner_ip}}/32
              if: always()
